/* tslint:disable */
/* eslint-disable */
/**
 * Amazon Ads API - Profiles
 * Profiles represent an advertiser and their account\'s marketplace, and are used in all subsequent API calls via a management scope, `Amazon-Advertising-API-Scope`. Reports and all entity management operations are associated with a single profile. Advertisers cannot have more than one profile for each marketplace.  Advertisers who operate in more than one marketplace (for example, Amazon.com, Amazon.co.uk, Amazon.co.jp) will have only one profile associated with each marketplace. [**See this link**](https://advertising.amazon.com/API/docs/en-us/info/api-overview#api-endpoints) for a list of marketplaces associated with each endpoint.  To retrieve your profile IDs, call the listProfiles operation, and include a valid authorization access token in the header. Use a `profileId` from the returned list as the value for the management scope (`Amazon-Advertising-API-Scope`) in the headers for subsequent API calls.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The countryCode for a given country
 * |Region|`countryCode`|Country Name|
 * |------|-----|-------|
 * |NA|BR|Brazil|
 * |NA|CA|Canada|
 * |NA|MX|Mexico|
 * |NA|US|United States|
 * |EU|AE|United Arab Emirates|
 * |EU|BE|Belgium| 
 * |EU|DE|Germany|
 * |EU|EG|Egypt|
 * |EU|ES|Spain|
 * |EU|FR|France|
 * |EU|IE|Ireland|
 * |EU|IN|India|
 * |EU|IT|Italy|
 * |EU|NL|The Netherlands|
 * |EU|PL|Poland|
 * |EU|SA|Saudi Arabia| 
 * |EU|SE|Sweden|  
 * |EU|TR|Turkey|
 * |EU|UK|United Kingdom|
 * |EU|ZA| South Africa |
 * |FE|AU|Australia|    
 * |FE|JP|Japan|
 * |FE|SG|Singapore|
 * @export
 */
export const CountryCode = {
    Br: 'BR',
    Ca: 'CA',
    Mx: 'MX',
    Us: 'US',
    Ae: 'AE',
    Be: 'BE',
    De: 'DE',
    Eg: 'EG',
    Es: 'ES',
    Fr: 'FR',
    Ie: 'IE',
    In: 'IN',
    It: 'IT',
    Nl: 'NL',
    Pl: 'PL',
    Sa: 'SA',
    Se: 'SE',
    Tr: 'TR',
    Uk: 'UK',
    Au: 'AU',
    Jp: 'JP',
    Sg: 'SG',
    Za: 'ZA'
} as const;
export type CountryCode = typeof CountryCode[keyof typeof CountryCode];


export function instanceOfCountryCode(value: any): boolean {
    for (const key in CountryCode) {
        if (Object.prototype.hasOwnProperty.call(CountryCode, key)) {
            if (CountryCode[key as keyof typeof CountryCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CountryCodeFromJSON(json: any): CountryCode {
    return CountryCodeFromJSONTyped(json, false);
}

export function CountryCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryCode {
    return json as CountryCode;
}

export function CountryCodeToJSON(value?: CountryCode | null): any {
    return value as any;
}

export function CountryCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): CountryCode {
    return value as CountryCode;
}

